import { createHash } from 'node:crypto'
import { aggregateMatrix, type MatrixReport } from './aggregate.js'
import { REQUIRED_ARTIFACTS } from './assertions/artifacts.js'
import { parseMatrixConfig } from './config.js'
import type { CaseEvidence, CaseStatus } from './types.js'

function stable(value: unknown, indent = 0): string {
  if (Array.isArray(value)) return `[${value.map((item) => stable(item, indent + 1)).join(',')}]`
  if (typeof value === 'object' && value !== null) {
    return `{${Object.entries(value as Record<string, unknown>)
      .filter(([, nested]) => nested !== undefined)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([key, nested]) => `${JSON.stringify(key)}:${stable(nested, indent + 1)}`)
      .join(',')}}`
  }
  return JSON.stringify(value)
}

export function serializeMatrixReport(report: MatrixReport): string {
  const projected = {
    ...report,
    cases: report.cases.map(projectCanonicalCase),
  }
  assertCanonicalSafety(projected)
  return `${stable(projected)}\n`
}

const SHA256 = /^[a-f0-9]{64}$/

function digest(value: unknown): string {
  return createHash('sha256').update(stable(value)).digest('hex')
}

function directGeneratorSummary(value: CaseEvidence['directGenerator']): Record<string, unknown> {
  if (
    value === undefined
    || value.discover.length !== 1
    || value.automatic.length !== 1
    || value.forced.length !== 1
  ) throw new Error('PASS case is missing direct-generator provenance')
  const discovery = value.discover[0]!
  const summarize = (emit: (typeof value.automatic)[number]) => {
    if (emit.remote === undefined) throw new Error('PASS case is missing Remote generator provenance')
    const contents: Record<string, string> = {
      'lib/typert.host.js': emit.js,
      'lib/typert.host.d.ts': emit.dts,
      'lib/typert.remote-client.js': emit.remote.js,
      'lib/typert.remote-client.d.ts': emit.remote.dts,
      'lib/typert.remote-client.d.ts.map': emit.remote.dtsMap,
    }
    return Object.fromEntries(REQUIRED_ARTIFACTS.map((artifact) => [
      artifact,
      createHash('sha256').update(contents[artifact]!).digest('hex'),
    ]))
  }
  return {
    schemaVersion: '1',
    discovery: {
      package: discovery.package,
      root: discovery.root,
      faces: discovery.faces,
    },
    automaticArtifactSha256: summarize(value.automatic[0]!),
    forcedArtifactSha256: summarize(value.forced[0]!),
  }
}

function passEvidenceRefs(value: Record<string, unknown>): string[] {
  return [
    `lock:sha256:${String(value.lockSha256)}`,
    `installed-graph:sha256:${String(value.installedGraphSha256)}`,
    `registry:sha256:${digest(value.registry)}`,
    `stages:sha256:${digest(value.stages)}`,
    `direct-generator:sha256:${digest(value.directGeneratorSummary)}`,
    `artifacts:sha256:${digest(value.artifacts)}`,
  ]
}

function projectCanonicalCase(input: CaseEvidence): Record<string, unknown> {
  const value = { ...input } as Record<string, unknown>
  delete value.directGenerator
  if (input.status === 'PASS') {
    value.directGeneratorSummary = directGeneratorSummary(input.directGenerator)
    const refs = passEvidenceRefs(value)
    value.assertions = input.assertions.map((assertion) => ({ ...assertion, evidenceRefs: refs }))
  }
  return value
}

const SENSITIVE_KEY = /(?:api.?key|token|secret|password|credential|authorization|cookie|private.?key|access.?key|session.?key)/i
const TOKEN_VALUE = /(?:\bgh[pousr]_[A-Za-z0-9_]{20,}\b|\bnpm_[A-Za-z0-9]{20,}\b|\bsk-[A-Za-z0-9_-]{16,}\b|\bBearer\s+[A-Za-z0-9._~+/=-]{16,}|\beyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+|\b[A-Za-z0-9_]*(?:API_KEY|TOKEN|SECRET|PASSWORD)=[^\s]+|-----BEGIN [A-Z ]*PRIVATE KEY-----)/i
const LOCAL_PATH = /^(?:\/|[A-Za-z]:[\\/]|file:\/\/|\\\\)/
const GENERATED_SOURCE_VALUE = /(?:\/\*\s*Generated by @deepseek-ai\/dsh-typert-generator|^(?:export|import)\s+(?:declare\s+)?(?:const|type|interface|class|function|\{))/m

function assertCanonicalSafety(value: unknown, at = 'report'): void {
  if (Array.isArray(value)) {
    value.forEach((item, index) => assertCanonicalSafety(item, `${at}[${index}]`))
    return
  }
  if (typeof value === 'object' && value !== null) {
    for (const [key, nested] of Object.entries(value as Record<string, unknown>)) {
      if (key === 'directGenerator' || (key !== 'cwdToken' && SENSITIVE_KEY.test(key))) {
        throw new Error(`report contains sensitive or forbidden canonical field ${at}.${key}`)
      }
      assertCanonicalSafety(nested, `${at}.${key}`)
    }
    return
  }
  if (typeof value === 'string') {
    if (TOKEN_VALUE.test(value)) throw new Error(`report contains a token-shaped value at ${at}`)
    if (LOCAL_PATH.test(value.trim())) throw new Error(`report contains an absolute local path at ${at}`)
    if (GENERATED_SOURCE_VALUE.test(value) || /[\r\n]/.test(value)) {
      throw new Error(`report contains sensitive raw source or log text at ${at}`)
    }
  }
}

function object(value: unknown, label: string): Record<string, unknown> {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new Error(`report ${label} must be an object`)
  }
  return value as Record<string, unknown>
}

const STATUSES = new Set<CaseStatus>([
  'PASS',
  'FAIL_COMPATIBILITY',
  'INCONCLUSIVE_REGISTRY',
  'INCONCLUSIVE_LOCK',
  'INCONCLUSIVE_ADAPTER',
  'INFRA_ERROR',
])

function parseCases(value: unknown): CaseEvidence[] {
  if (!Array.isArray(value)) throw new Error('report cases must be an array')
  return value.map((input) => {
    const item = object(input, 'case')
    const matrixCase = object(item.case, 'matrix case')
    if (typeof matrixCase.id !== 'string' || typeof matrixCase.role !== 'string') {
      throw new Error('report matrix case identity is invalid')
    }
    if (!STATUSES.has(item.status as CaseStatus)) throw new Error('report case status is invalid')
    if (!Array.isArray(item.assertions) || !Array.isArray(item.artifacts)) {
      throw new Error('report case evidence arrays are invalid')
    }
    for (const assertion of item.assertions) {
      const entry = object(assertion, 'assertion')
      if (
        typeof entry.id !== 'string'
        || !['PASS', 'FAIL', 'BLOCKED'].includes(String(entry.status))
        || !Array.isArray(entry.evidenceRefs)
      ) throw new Error('report assertion is invalid')
    }
    for (const artifact of item.artifacts) {
      const entry = object(artifact, 'artifact')
      if (
        typeof entry.path !== 'string'
        || typeof entry.size !== 'number'
        || entry.size <= 0
        || typeof entry.sha256 !== 'string'
        || !/^[a-f0-9]{64}$/.test(entry.sha256)
        || typeof entry.createdAtMs !== 'number'
      ) throw new Error('report artifact is invalid')
    }
    if (item.status === 'PASS') validatePassProvenance(item)
    return item as unknown as CaseEvidence
  })
}

function exactKeys(value: Record<string, unknown>, allowed: readonly string[], label: string): void {
  const extra = Object.keys(value).find((key) => !allowed.includes(key))
  if (extra !== undefined) throw new Error(`report ${label} has unknown key ${extra}`)
}

function hashRecord(value: unknown, label: string): Record<string, unknown> {
  const result = object(value, label)
  exactKeys(result, REQUIRED_ARTIFACTS, label)
  for (const artifact of REQUIRED_ARTIFACTS) {
    if (typeof result[artifact] !== 'string' || !SHA256.test(result[artifact])) {
      throw new Error(`report ${label} has invalid artifact hash`)
    }
  }
  return result
}

function validatePassProvenance(item: Record<string, unknown>): void {
  if (typeof item.lockSha256 !== 'string' || !SHA256.test(item.lockSha256)) {
    throw new Error('report PASS case lockSha256 provenance is invalid')
  }
  if (typeof item.installedGraphSha256 !== 'string' || !SHA256.test(item.installedGraphSha256)) {
    throw new Error('report PASS case installedGraphSha256 provenance is invalid')
  }
  if (!Array.isArray(item.registry) || item.registry.length !== 5) {
    throw new Error('report PASS case registry provenance is incomplete')
  }
  if (!Array.isArray(item.stages) || item.stages.length < 10) {
    throw new Error('report PASS case stage provenance is incomplete')
  }
  for (const stage of item.stages) {
    const entry = object(stage, 'stage provenance')
    if (
      entry.exitCode !== 0
      || entry.timedOut !== false
      || entry.signal !== null
      || typeof entry.stdoutSha256 !== 'string'
      || !SHA256.test(entry.stdoutSha256)
      || typeof entry.stderrSha256 !== 'string'
      || !SHA256.test(entry.stderrSha256)
    ) throw new Error('report PASS case stage provenance is invalid')
  }
  const summary = object(item.directGeneratorSummary, 'direct-generator summary')
  exactKeys(
    summary,
    ['schemaVersion', 'discovery', 'automaticArtifactSha256', 'forcedArtifactSha256'],
    'direct-generator summary',
  )
  if (summary.schemaVersion !== '1') throw new Error('report direct-generator summary version is invalid')
  const discovery = object(summary.discovery, 'direct-generator discovery')
  if (
    discovery.package !== '@knight/dsh-typert-matrix-probe'
    || discovery.root !== 'packages/probe'
    || stable(discovery.faces) !== stable(['host'])
  ) throw new Error('report direct-generator discovery provenance is invalid')
  const automatic = hashRecord(summary.automaticArtifactSha256, 'automatic artifact hashes')
  const forced = hashRecord(summary.forcedArtifactSha256, 'forced artifact hashes')
  const artifacts = item.artifacts as Array<Record<string, unknown>>
  for (const artifact of REQUIRED_ARTIFACTS) {
    const observed = artifacts.find(({ path }) => path === artifact)
    if (
      observed === undefined
      || automatic[artifact] !== observed.sha256
      || forced[artifact] !== observed.sha256
    ) throw new Error(`report PASS case direct-generator provenance does not match ${artifact}`)
  }
  const expectedRefs = passEvidenceRefs(item)
  for (const assertion of item.assertions as Array<Record<string, unknown>>) {
    if (stable(assertion.evidenceRefs) !== stable(expectedRefs)) {
      throw new Error('report PASS assertion evidence reference does not close over case provenance')
    }
  }
}

export function parseAndVerifyReport(raw: string): MatrixReport {
  const value = object(JSON.parse(raw), 'root')
  assertCanonicalSafety(value)
  exactKeys(value, [
    'schemaVersion', 'runId', 'config', 'environment', 'cases', 'eligibleCandidateIds',
    'incompleteCaseIds', 'exitCode', 'exitReason', 'decision', 'humanDecisionRequired',
    'evidenceBoundary',
  ], 'root')
  if (value.schemaVersion !== '1' || typeof value.runId !== 'string') {
    throw new Error('report identity is invalid')
  }
  const config = parseMatrixConfig(value.config)
  const cases = parseCases(value.cases)
  const environment = object(value.environment, 'environment')
  const recomputed = aggregateMatrix(config, cases, {
    runId: value.runId,
    platform: String(environment.platform),
    arch: String(environment.arch),
    node: String(environment.node),
    npmCli: String(environment.npmCli),
  })
  for (const field of [
    'exitCode',
    'exitReason',
    'decision',
    'humanDecisionRequired',
    'evidenceBoundary',
  ] as const) {
    if (stable(value[field]) !== stable(recomputed[field])) {
      throw new Error(`report aggregate mismatch for ${field}`)
    }
  }
  if (
    stable(value.eligibleCandidateIds) !== stable(recomputed.eligibleCandidateIds)
    || stable(value.incompleteCaseIds) !== stable(recomputed.incompleteCaseIds)
  ) throw new Error('report aggregate mismatch for case lists')
  return recomputed
}
