import { createHash } from 'node:crypto'
import { readFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { beforeAll, describe, expect, test } from 'vitest'
import { aggregateMatrix, REQUIRED_PASS_ASSERTIONS } from '../src/aggregate.js'
import { REQUIRED_ARTIFACTS } from '../src/assertions/artifacts.js'
import { parseMatrixConfig } from '../src/config.js'
import { renderJUnit } from '../src/report-junit.js'
import { parseAndVerifyReport, serializeMatrixReport } from '../src/report-json.js'
import { renderMarkdown } from '../src/report-markdown.js'
import { redactText } from '../src/redact.js'
import type { CaseEvidence, MatrixConfig } from '../src/types.js'

let config: MatrixConfig
let cases: CaseEvidence[]

const sha256 = (value: string): string => createHash('sha256').update(value).digest('hex')
const fakeGitHubToken = ['ghp_', 'abcdefghijklmnopqrstuvwxyz0123456789'].join('')
const fakeBearerToken = [
  'Bearer ',
  'eyJhbGciOiJIUzI1NiJ9.',
  'eyJzdWIiOiJ1c2VyIn0.',
  'signature',
].join('')

const generated = {
  'lib/typert.host.js': '/* Generated by @deepseek-ai/dsh-typert-generator */\nexport const host = true\n',
  'lib/typert.host.d.ts': '/* Generated by @deepseek-ai/dsh-typert-generator */\nexport declare const host: true\n',
  'lib/typert.remote-client.js': '/* Generated by @deepseek-ai/dsh-typert-generator */\nexport const remote = true\n',
  'lib/typert.remote-client.d.ts': '/* Generated by @deepseek-ai/dsh-typert-generator */\nexport declare const remote: true\n',
  'lib/typert.remote-client.d.ts.map': '{"version":3,"file":"typert.remote-client.d.ts","sources":["../src/index.ts"]}',
} as const

function processStage(program: 'npm-cli' | 'typescript' | 'tsdown' | 'workspace-adapter', index: number) {
  return {
    program,
    args: [`stage-${index}`],
    cwdToken: '<workspace>' as const,
    startedAt: '2026-09-02T00:00:00.000Z',
    durationMs: index + 1,
    exitCode: 0,
    signal: null,
    timedOut: false,
    stdoutSha256: sha256(`stdout-${index}`),
    stderrSha256: sha256(`stderr-${index}`),
    stdoutTruncated: false,
    stderrTruncated: false,
  }
}

function passingEvidence(matrixCase: MatrixConfig['cases'][number]): CaseEvidence {
  const release = matrixCase.release['@deepseek-ai/dsh']
  const directEmit = {
    package: '@knight/dsh-typert-matrix-probe',
    packageRoot: 'packages/probe',
    face: 'host',
    exports: ['.'],
    js: generated['lib/typert.host.js'],
    dts: generated['lib/typert.host.d.ts'],
    remote: {
      js: generated['lib/typert.remote-client.js'],
      dts: generated['lib/typert.remote-client.d.ts'],
      dtsMap: generated['lib/typert.remote-client.d.ts.map'],
    },
  }
  const stages = [
    ...Array.from({ length: 7 }, (_, index) => processStage('npm-cli', index)),
    processStage('typescript', 7),
    processStage('workspace-adapter', 8),
    processStage('tsdown', 9),
    processStage('npm-cli', 10),
  ]
  return {
    schemaVersion: '1',
    case: matrixCase,
    status: 'PASS',
    assertions: REQUIRED_PASS_ASSERTIONS.map((id) => ({
      id,
      status: 'PASS',
      expected: true,
      actualSummary: true,
      evidenceRefs: [],
    })),
    artifacts: REQUIRED_ARTIFACTS.map((artifactPath, index) => ({
      path: artifactPath,
      size: Buffer.byteLength(generated[artifactPath]),
      sha256: sha256(generated[artifactPath]),
      createdAtMs: 1_788_259_200_000 + index,
    })),
    lockSha256: sha256('lock'),
    installedGraphSha256: sha256('installed-graph'),
    registry: [
      '@deepseek-ai/dsh',
      '@deepseek-ai/dsh-typert-generator',
      '@deepseek-ai/dsh-typert-protocol',
      '@deepseek-ai/dsh-invariants',
      '@deepseek-ai/cordis',
    ].map((name) => {
      const version = name === '@deepseek-ai/cordis'
        ? matrixCase.packages['@deepseek-ai/cordis']
        : release
      return {
        name,
        requestedVersion: version,
        returnedVersion: version,
        integrity: `sha512-${Buffer.from(`${name}@${version}`).toString('base64')}`,
        tarballOrigin: 'https://registry.npmjs.org',
        ...(name === '@deepseek-ai/cordis'
          ? {}
          : { repositoryUrl: 'git+https://github.com/deepseek-ai/deepseek-harness.git' }),
        observedAt: '2026-09-02T00:00:00.000Z',
      }
    }) as NonNullable<CaseEvidence['registry']>,
    stages,
    directGenerator: {
      discover: [{
        package: '@knight/dsh-typert-matrix-probe',
        root: 'packages/probe',
        faces: ['host'],
      }],
      automatic: [directEmit],
      forced: [structuredClone(directEmit)],
    },
    nonDecisiveDiagnostics: { ordinaryBundleIsDecisive: false },
  }
}

function reportWithPassingCandidate() {
  const candidate = config.cases.find(({ role }) => role === 'candidate')!
  const passCases = cases.map((entry) => (
    entry.case.id === candidate.id ? passingEvidence(candidate) : entry
  ))
  return aggregateMatrix(config, passCases, { runId: 'passing-run' })
}

beforeAll(async () => {
  config = parseMatrixConfig(JSON.parse(await readFile(
    fileURLToPath(new URL('../config/matrix.official.json', import.meta.url)),
    'utf8',
  )))
  cases = config.cases.map((matrixCase) => ({
    schemaVersion: '1',
    case: matrixCase,
    status: 'FAIL_COMPATIBILITY',
    assertions: [{ id: 'B03', status: 'FAIL', expected: 1, actualSummary: 0, evidenceRefs: ['cases/log.sha256'] }],
    artifacts: [],
    failure: { code: 'GENERATION_EMPTY', stage: 'direct-generator' },
  }))
})

describe('canonical reports', () => {
  test('serializes deterministically and verifies aggregate semantics on readback', () => {
    const report = aggregateMatrix(config, cases, { runId: 'fixed-run' })
    const first = serializeMatrixReport(report)
    const second = serializeMatrixReport(report)

    expect(first).toBe(second)
    expect(parseAndVerifyReport(first)).toEqual(report)
  })

  test('rejects a tampered exit code or eligible-candidate list', () => {
    const report = aggregateMatrix(config, cases, { runId: 'fixed-run' })
    const tampered = { ...report, exitCode: 0, eligibleCandidateIds: ['invented'] }

    expect(() => parseAndVerifyReport(JSON.stringify(tampered))).toThrow(/aggregate mismatch/)
  })

  test('derives Markdown and JUnit from canonical JSON with the compatibility disclaimer', () => {
    const canonical = parseAndVerifyReport(serializeMatrixReport(
      aggregateMatrix(config, cases, { runId: 'fixed-run' }),
    ))

    const markdown = renderMarkdown(canonical)
    const junit = renderJUnit(canonical)
    expect(markdown).toContain('does not prove full DeepSeek Harness compatibility')
    expect(markdown).toContain('| Typert cohort | Role | Result |')
    expect(junit).toContain('<testsuite')
    expect(junit).toContain('GENERATION_EMPTY')
  })

  test('redacts absolute roots and token-shaped values before report inclusion', () => {
    const input = `path=/sensitive/repo token=${fakeGitHubToken} API_KEY=super-secret`

    expect(redactText(input, ['/sensitive/repo'])).toBe(
      'path=<repo> token=<redacted> API_KEY=<redacted>',
    )
  })

  test('canonicalizes a real PASS to hash-only direct-generator evidence and closed hash refs', () => {
    const raw = serializeMatrixReport(reportWithPassingCandidate())
    const parsed = parseAndVerifyReport(raw)
    const passing = parsed.cases.find(({ status }) => status === 'PASS')!

    expect(raw).not.toContain('export const host = true')
    expect(raw).not.toContain('export declare const remote: true')
    expect(raw).not.toContain('"directGenerator":')
    expect(passing).toHaveProperty('directGeneratorSummary')
    expect(passing.assertions).toHaveLength(REQUIRED_PASS_ASSERTIONS.length)
    expect(passing.assertions.every(({ evidenceRefs }) => evidenceRefs.length === 6)).toBe(true)
    expect(passing.assertions.flatMap(({ evidenceRefs }) => evidenceRefs))
      .toSatisfy((refs: string[]) => refs.every((ref) => /^[a-z-]+:sha256:[a-f0-9]{64}$/.test(ref)))
  })

  test('rejects a hand-written PASS made only from assertion ids and five placeholder artifacts', () => {
    const report = reportWithPassingCandidate()
    const input = structuredClone(report) as unknown as Record<string, unknown>
    const reportCases = input.cases as Array<Record<string, unknown>>
    const passing = reportCases.find(({ status }) => status === 'PASS')!
    delete passing.lockSha256
    delete passing.installedGraphSha256
    delete passing.registry
    delete passing.stages
    delete passing.directGenerator
    passing.artifacts = REQUIRED_ARTIFACTS.map((artifactPath) => ({
      path: artifactPath,
      size: 1,
      sha256: 'a'.repeat(64),
      createdAtMs: 1,
    }))

    expect(() => parseAndVerifyReport(JSON.stringify(input))).toThrow(/PASS.*provenance|lockSha256/i)
  })

  test('rejects a PASS when an assertion hash reference does not close over case evidence', () => {
    const canonical = JSON.parse(serializeMatrixReport(reportWithPassingCandidate())) as {
      cases: Array<{ status: string; assertions: Array<{ evidenceRefs: string[] }> }>
    }
    const passing = canonical.cases.find(({ status }) => status === 'PASS')!
    passing.assertions[0]!.evidenceRefs[0] = `lock:sha256:${sha256('invented')}`

    expect(() => parseAndVerifyReport(JSON.stringify(canonical))).toThrow(/evidence reference|provenance/i)
  })

  test.each([
    ['sensitive field', 'apiToken', 'safe-looking-value'],
    ['GitHub token value', 'diagnostic', fakeGitHubToken],
    ['bearer token value', 'diagnostic', fakeBearerToken],
    ['absolute local path', 'diagnostic', '/Users/private/source.ts'],
    ['generic absolute local path', 'diagnostic', '/etc/private-runner.conf'],
    ['secret assignment value', 'diagnostic', 'API_KEY=super-secret-value'],
    ['generated source value', 'diagnostic', 'export const leakedGeneratedSource = true'],
  ])('recursively rejects %s while writing and verifying canonical JSON', (_label, key, value) => {
    const report = aggregateMatrix(config, cases, { runId: 'unsafe-run' })
    const unsafeCase = report.cases[0] as CaseEvidence & { nonDecisiveDiagnostics: Record<string, unknown> }
    const unsafeReport = {
      ...report,
      cases: [
        { ...unsafeCase, nonDecisiveDiagnostics: { ordinaryBundleIsDecisive: false, [key]: value } },
        ...report.cases.slice(1),
      ],
    }

    expect(() => serializeMatrixReport(unsafeReport)).toThrow(/sensitive|token|absolute|unknown/i)
    expect(() => parseAndVerifyReport(JSON.stringify(unsafeReport))).toThrow(/sensitive|token|absolute|unknown/i)
  })

  test('rejects raw direct-generator source fields in a purported canonical report', () => {
    const canonical = JSON.parse(serializeMatrixReport(reportWithPassingCandidate())) as {
      cases: Array<Record<string, unknown>>
    }
    const passing = canonical.cases.find(({ status }) => status === 'PASS')!
    passing.directGenerator = {
      automatic: [{ js: 'export const forged = true' }],
    }

    expect(() => parseAndVerifyReport(JSON.stringify(canonical))).toThrow(/directGenerator|source|unknown/i)
  })
})
