import { createHash } from 'node:crypto'
import { lstat, readFile, realpath } from 'node:fs/promises'
import path from 'node:path'
import type { ArtifactEvidence } from '../types.js'
import type { ExpectedArtifactContents } from './generation.js'
import { CompatibilityEvidenceError } from './errors.js'

export const REQUIRED_ARTIFACTS = [
  'lib/typert.host.js',
  'lib/typert.host.d.ts',
  'lib/typert.remote-client.js',
  'lib/typert.remote-client.d.ts',
  'lib/typert.remote-client.d.ts.map',
] as const

function sha256(value: Buffer | string): string {
  return createHash('sha256').update(value).digest('hex')
}

function inside(root: string, target: string): boolean {
  const relative = path.relative(root, target)
  return relative === '' || (!relative.startsWith('..') && !path.isAbsolute(relative))
}

function equal(left: unknown, right: unknown): boolean {
  return JSON.stringify(left) === JSON.stringify(right)
}

export async function assertArtifactsAbsent(probeRoot: string): Promise<void> {
  for (const relative of REQUIRED_ARTIFACTS) {
    try {
      await lstat(path.join(probeRoot, relative))
      throw new CompatibilityEvidenceError(
        'PRESEEDED_ARTIFACT',
        `generated artifact was present before generation: ${relative}`,
      )
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
    }
  }
}

export interface ArtifactInspectionRequest {
  readonly probeRoot: string
  readonly expected: ExpectedArtifactContents
  readonly startedAtMs: number
  readonly manifest: Record<string, unknown>
  readonly packFiles: readonly string[]
}

export async function inspectGeneratedArtifacts(
  request: ArtifactInspectionRequest,
): Promise<readonly ArtifactEvidence[]> {
  const probeReal = await realpath(request.probeRoot)
  const evidence: ArtifactEvidence[] = []
  for (const relative of REQUIRED_ARTIFACTS) {
    const absolute = path.join(probeReal, relative)
    let info
    try {
      info = await lstat(absolute)
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
        throw new CompatibilityEvidenceError('ARTIFACT_MISSING', `generated artifact is missing: ${relative}`)
      }
      throw error
    }
    if (info.isSymbolicLink()) {
      throw new CompatibilityEvidenceError('ARTIFACT_SYMLINK', `artifact is a symlink: ${relative}`)
    }
    if (!info.isFile()) {
      throw new CompatibilityEvidenceError('ARTIFACT_NOT_REGULAR', `artifact is not regular: ${relative}`)
    }
    const artifactReal = await realpath(absolute)
    if (!inside(probeReal, artifactReal)) {
      throw new CompatibilityEvidenceError('ARTIFACT_BOUNDARY', `artifact is outside probe: ${relative}`)
    }
    if (info.size === 0) {
      throw new CompatibilityEvidenceError('ARTIFACT_EMPTY', `artifact is empty: ${relative}`)
    }
    if (info.mtimeMs < request.startedAtMs) {
      throw new CompatibilityEvidenceError('ARTIFACT_STALE', `artifact is stale: ${relative}`)
    }
    const content = await readFile(absolute)
    if (sha256(content) !== sha256(request.expected[relative])) {
      throw new CompatibilityEvidenceError(
        'ARTIFACT_HASH_MISMATCH',
        `artifact differs from direct generator output: ${relative}`,
      )
    }
    if (!relative.endsWith('.map') && !content.toString('utf8').startsWith(
      '/* Generated by @deepseek-ai/dsh-typert-generator',
    )) {
      throw new CompatibilityEvidenceError('ARTIFACT_HEADER', `artifact header is invalid: ${relative}`)
    }
    evidence.push({ path: relative, size: info.size, sha256: sha256(content), createdAtMs: info.mtimeMs })
  }

  let sourceMap: { file?: unknown; sources?: unknown }
  try {
    sourceMap = JSON.parse(
      await readFile(path.join(probeReal, 'lib/typert.remote-client.d.ts.map'), 'utf8'),
    ) as { file?: unknown; sources?: unknown }
  } catch {
    throw new CompatibilityEvidenceError('SOURCE_MAP_INVALID', 'Remote declaration source map is invalid JSON')
  }
  if (sourceMap.file !== 'typert.remote-client.d.ts' || !Array.isArray(sourceMap.sources)) {
    throw new CompatibilityEvidenceError('SOURCE_MAP_INVALID', 'Remote declaration source map is invalid')
  }
  for (const source of sourceMap.sources) {
    if (
      typeof source !== 'string'
      || path.isAbsolute(source)
      || source.startsWith('file:')
      || /^[A-Za-z]:[\\/]/.test(source)
    ) {
      throw new CompatibilityEvidenceError('SOURCE_MAP_ABSOLUTE', 'source map contains an absolute local path')
    }
  }

  const exportsValue = request.manifest.exports as Record<string, unknown> | undefined
  if (
    exportsValue === undefined
    || !equal(exportsValue['./typert'], {
      types: './lib/typert.host.d.ts',
      default: './lib/typert.host.js',
    })
    || !equal(exportsValue['./remote'], {
      types: './lib/typert.remote-client.d.ts',
      default: './lib/typert.remote-client.js',
    })
  ) throw new CompatibilityEvidenceError('PACKAGE_EXPORTS', 'package exports do not map Typert artifacts exactly')

  const manifestFiles = request.manifest.files
  if (!Array.isArray(manifestFiles) || REQUIRED_ARTIFACTS.some((entry) => !manifestFiles.includes(entry))) {
    throw new CompatibilityEvidenceError('PACKAGE_FILES', 'package files whitelist omits a Typert artifact')
  }

  const normalizedPack = request.packFiles.map((entry) => entry.replace(/^package\//, ''))
  for (const relative of REQUIRED_ARTIFACTS) {
    if (!normalizedPack.includes(relative)) {
      throw new CompatibilityEvidenceError('PACK_ARTIFACT_MISSING', `pack is missing artifact ${relative}`)
    }
  }
  const forbidden = normalizedPack.find((entry) =>
    /(^|\/)(node_modules|npm-cache|tests|\.tmp|logs)(\/|$)|(^|\/)npmrc$|\.env(?:\.|$)/.test(entry),
  )
  if (forbidden !== undefined || normalizedPack.some((entry) => path.isAbsolute(entry))) {
    throw new CompatibilityEvidenceError('PACK_FORBIDDEN_FILE', `pack contains forbidden file ${forbidden ?? ''}`)
  }
  return evidence
}
